template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "czec1258"
__REPO__ = "lang-ces"
__UND2C__ = "cs"
__UNDEFINED__ = "Czech"
__UND__ = "ces"
