template = "https://github.com/giellalt/template-lang-und"
rev_id = 254
template_sha = "9eb2a95995f59cb63a159a5cc7bcce8f049babe4"

[replacements]
__GLOTTOLOG_ID__ = "czec1258"
__REPO__ = "lang-ces"
__UND2C__ = "cs"
__UNDEFINED__ = "Czech"
__UND__ = "ces"
